config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'postings#index'
  get 'my_postings', to: 'pages#user_postings'
  get 'my_bookings', to: 'pages#user_bookings'
  resources :postings do
    resources :bookings, only: [:new, :create, :destroy]
  end # only: [:index, :new, :create, :show, :destroy, :edit,]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :posting

  validates :occurs_on, uniqueness: true
  validates :user_id, uniqueness: { scope: :posting_id, message: "cannot book your own post" }
end

app/models/posting.rb
class Posting < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos

  validates :cuisine, presence: true
  validates :price, presence: true
  validates :bio, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :postings
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: :destroy
  before_action :set_posting, only: [:new, :create]

  def new
    @booking = Booking.new
    authorize @posting
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.posting = @posting
    if @booking.save
      redirect_to my_bookings_path
    else
      render "postings/show"
    end
    authorize @posting
  end

  def destroy
    @booking.destroy
    redirect_to posting_path(@booking.posting)
  end

  private

  def booking_params
    params.require(:booking).permit(:occurs_on, :diners)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_posting
    @posting = Posting.find(params[:posting_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def user_postings
    @postings = current_user.postings
  end

  def user_bookings
    @bookings = current_user.bookings
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: %i[show edit update destroy]

  def index
    @postings = policy_scope(Posting)
    @posting = Posting.new
  end

  def show
    @booking = Booking.new
    # @posting = Posting.find(params[:id])
  end

  def new
    @posting = Posting.new
    authorize @posting
  end

  def create
    @posting = Posting.new(posting_params)
    @posting.user = current_user

    if @posting.save
      redirect_to posting_path(@posting)
    else
      render :new
    end
    authorize @posting
  end

  def edit
    # @posting = Posting.find(params[:id])
  end

  def update
    # @posting = Posting.find(params[:id])
    if @posting.update(posting_params)
      redirect_to postings_path
    else
      render :new
    end
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def destroy
    # @posting = Posting.find(params[:id])
    @posting.destroy
    redirect_to postings_path
  end

  private

  def set_posting
    @posting = Posting.find(params[:id])
    authorize @posting
  end

  def posting_params
    params.require(:posting).permit(:cuisine, :price, :bio, :name, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chefbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/user_bookings.html.erb
<div class="banner" style="background-image: url(https://images.pexels.com/photos/357743/pexels-photo-357743.jpeg?auto=compress&cs=tinysrgb&w=1600)">
  <%= render 'shared/navbar' %>
  <div class="container">
    <h1>The perfect cook for</h1>
    <h1>the perfect meal</h1>
  </div>
</div>

<div class="container-index">
  <div class="index-display">
    <% @bookings.each do |booking| %>
      <%= link_to posting_path(id = booking.posting_id) do %>
      <div class="card-bookings">
        <div class="card-bookings-infos">
          <h2><%= Posting.find(id = booking.posting_id).name%></h2>
          <p><%= booking.occurs_on  %></p>
          <p><%= Posting.find(id = booking.posting_id).bio[0..100]%>...</p>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/user_postings.html.erb
<%= render 'shared/navbar2' %>
<div class="container-bdy">
  <h2>MY POSTINGS</h2>
</div>
  <div class="index-display">
    <% @postings.each do |posting| %>
      <%= render 'shared/cardposting', posting: posting %>
    <% end %>
  </div>

app/views/postings/_form.html.erb
<div class="container-form">
  <div class="form">
    <%= simple_form_for(@posting) do |f| %>
            <%= f.input :name, placeholder: 'Name' %>
            <%= f.input :cuisine, placeholder: 'Cuisine' %>
            <%= f.input :price, placeholder: 'Price' %>
            <%= f.input :bio, placeholder: 'Bio' %>
            <%= f.input :photos, input_html: { multiple: true } %>
            <%= f.submit class: 'btn btn-gradient' %>
          <% end %>
  </div>
</div>

app/views/postings/edit.html.erb
<%=  render 'shared/navbar2' %>
 <div class="form-div">
    <div class="edit-title">
      <h2> Edit Postings </h2>
    </div>
    <div class="dlt-btn">
      <% if current_user == @posting.user %>
        <button class="btn-show"><%= link_to "Delete", posting_path(@posting),method: :delete, data: {confirm: "Are you sure?"} %></button>
      <%end%>
    </div>
  </div>
<div class="form-container">
  <%= render 'form', posting: @posting %>
</div>
<%= link_to "Back to Post", posting_path %>

app/views/postings/index.html.erb
<div class="banner" style="background-image: url(https://images.pexels.com/photos/357743/pexels-photo-357743.jpeg?auto=compress&cs=tinysrgb&w=1600)">
  <%= render 'shared/navbar' %>
  <div class="container">
  <div class="h1-div">
    <h1>The perfect cook for</h1>
    <h1>the perfect meal</h1>
  </div>
    <%= link_to "Create new posting", new_posting_path, class:"new-post-btn" %>
  </div>
</div>

<div class="container-index">
  <div class="index-display">
    <% @postings.each do |posting| %>
      <%= render 'shared/cardposting', posting: posting %>
    <% end %>
  </div>
</div>

app/views/postings/new.html.erb
<%=  render 'shared/navbar2' %>
<div class="form-header">
    <h2> Create Postings </h2>
  </div>
<div class="form-container">
  <%= render 'form' %>
</div>

app/views/postings/show.html.erb
<%=  render 'shared/navbar2' %>
<div class="container">
  <h1><%= @posting.name %></h1>
  <div class="image-grid">
    <% @posting.photos.each_with_index do |photo, i| %>
      <% if i > 0 %>
        <%= cl_image_tag photo.key, class:"img"  %>
      <% else %>
        <%= cl_image_tag photo.key, class:"image-grid-row-2" %>
        <% end %>
    <% end %>
  </div>
  <div class="card-price">
    <div class="left">
      <div class="show-desc">
        <h2><%= @posting.cuisine %></h2>
        <p><%= @posting.bio %></p>
      </div>
      <hr class=line>
    </div>
    <div class="right">
      <%= render 'shared/pricecardposting' %>
    </div>
  </div>
  <%# <%= link_to "Show all postings", postings_path %>
  <% if current_user == @posting.user %>
    <button class="btn-show"><%= link_to "Edit", edit_posting_path(@posting) %></button>
  <%end%>
</div>

app/views/shared/_button.html.erb
<%= link_to "Create Posting", "#", class: "btn btn-gradient" %>

app/views/shared/_cardposting.html.erb
<%= link_to posting_path(posting) do %>
  <section>
    <div class="cards">
      <div class="top test" style="background-image: url('<%= !posting.photos[0].nil? ? (cl_image_path posting.photos[0]&.key, crop: :fill): "" %>')"></div>
      <div class="bottom">
        <div class="card-infos">
            <div class="btn"><%= posting.cuisine %></div>
            <div class="cont-info">
            <h2><%= posting.name %>
            <p><%= posting.bio[0..60]%>...</p>
            </div>
            <h2 class="card-pricing">$<%= posting.price %></h2>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-white">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-0">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to postings_path, class: "navbar-brand" do %>
      <h2>ChefBook</h2>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Bookings", my_bookings_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Create a posting", new_posting_path, class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item active">
            <%= link_to "Postings", my_postings_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item active">
            <%= link_to "About Us", "#", class: "nav-link" %>
          <%# </li> %>
           <li class="nav-item active">
            <%= link_to "Contact Us", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.pexels.com/photos/2023386/pexels-photo-2023386.jpeg?auto=compress&cs=tinysrgb&w=1600", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Create a posting", new_posting_path, class: "dropdown-item" %>
              <%# <%= link_to "My Postings", my_postings_path, class: "dropdown-item" %>
              <%= link_to "About us", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-show">
  <div class="container-fluid">
    <%= link_to postings_path, class: "navbar-brand" do %>
      <h2>ChefBook</h2>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create a posting", new_posting_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", my_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Postings", my_postings_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item active">
            <%= link_to "About Us", "#", class: "nav-link" %>
          <%# </li> %>
           <li class="nav-item active">
            <%= link_to "Contact Us", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.pexels.com/photos/2023386/pexels-photo-2023386.jpeg?auto=compress&cs=tinysrgb&w=1600", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "About us", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pricecardposting.html.erb
<div class="card">
  <div class="card-body">
    <div class="check-form">
      <h5 class="card-title">$<%= @posting.price %></h5>
      <p class="card-text">Reviews</p>
    </div>
    <div class="cont-form">
      <%= simple_form_for [@posting, @booking] do |f| %>
            <%= f.input :occurs_on, as: :date, label: false, html5: true %>
            <%# <%= f.input :diners, label: false, placeholder: 'Select number of guests' %>
            <%= f.submit class: 'btn btn-flat' %>
          <% end %>
    </div>
    <div class="check-form-start">
      <ul style="list-style: none; padding-left: 0;">
        <li>$<%= @posting.price %></li>
        <li>Service fee</li>
        <li>Taxes</li>
      </ul>
      <ul style="list-style: none; padding-left: 0;">
        <li>$<%= @posting.price%></li>
        <li>$<%= 22 %></li>
        <li>$<%= 18 %></li>
      </ul>
    </div>
    <hr class=solid>
  </div>
    <div class="check-form-end">
    <div class="r"><h4>Total</h4></div>
    <div class="l"><h4>$<%= @posting.price + 22 + 18 %></h4></div>
    </div>
</div>

app/views/users/index.html.erb
<div class="banner" style="background-image: url(https://images.pexels.com/photos/357743/pexels-photo-357743.jpeg?auto=compress&cs=tinysrgb&w=1600)">
  <%= render 'shared/navbar' %>
  <div class="container">
    <h1>The perfect cook for</h1>
    <h1>the perfect meal</h1>
  </div>
</div>

<div class="container-index">
  <div class="index-display">
    <% @postings.each do |posting| %>
    <% if posting.user == current_user %>
      <%= render 'shared/cardposting', posting: posting %>
    <% end %>
    <% end %>
  </div>
</div>